feat: Strapi API Integration
Kites-Foundation/hello-munnar-frontend pull request #292
Opened 2022-04-11 09:51 UTC by naseemshah

# Explain the feature/fix

This PR includes API integration from Strapi backend and partial user authentication is implemented (Integrated Google Login Button and Receiving JWT token from Strapi)

API Integrated:
- KSTRC
- Destination Page
- Activity Page
- Review Page (only retrieving reviews, Adding Review feature after complete implementation of authentication)

2022-04-13 02:51 UTC, riginoommen requested changes

2022-04-16 12:51 UTC, lespaceman commented on src/components/Common/Heading.js
> +        let formatedAvailableDays = [];
let formatedAvailableDays = availableDays.map(...

2022-04-16 12:53 UTC, lespaceman commented on src/components/Common/Rails/Carousal/CarousalCard.js
> +            console.log("here");
Remove console.log()

2022-04-16 12:56 UTC, lespaceman commented on src/components/User/SignIn.js
> +                    console.log(data);
remove console.log()

2022-04-16 12:56 UTC, lespaceman commented on src/router/PublicRouter.js
> +    // useEffect(() => {
remove commented code

2022-04-16 12:56 UTC, lespaceman commented on src/components/Ksrtc/KsrtcContainer.js
> +                    console.log(data);
remove console.log()

2022-04-16 13:30 UTC, gautamkrishnar requested changes

2022-04-25 15:53 UTC, lespaceman approved these changes

2022-04-25 21:28 UTC, gautamkrishnar approved these changes

2022-04-25 21:29 UTC, merged