/Nearme book a guide card
Kites-Foundation/hello-munnar-frontend pull request #45
Opened 2021-01-30 19:36 UTC by Michellejacob001

# Closes/Fixes/Resolves

Fixes #41

# Explain the feature/fix

Added the card component of the bookguide and callbookmark(wrapper) to nearme file.

## Does this PR introduce a breaking change

No

## Screenshots

![Screenshot (186)](https://user-images.githubusercontent.com/62324802/106366196-3d37a800-6360-11eb-84b7-1479781e2076.png)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-01-30 20:40 UTC, rejahrehim requested changes

2021-01-30 20:40 UTC, rejahrehim commented on src/components/NearMe/bookguide.js
> +                <img
Use icons from icon  library, Like font-awesome

2021-01-30 22:30 UTC, riginoommen commented
PR on hold

2021-02-01 05:14 UTC, closed without merging

2021-02-01 05:16 UTC, Michellejacob001 commented
Another PR is sent by Fayaz.